'use client';

import { createContext, useEffect, useState } from 'react';
import { TelemetrySnapshot } from '../config/types';

type SnapshotContextType = {
  allSnapshots: TelemetrySnapshot[];
  currentSnapshot: TelemetrySnapshot | null;
  futureSnapshots: TelemetrySnapshot[];
  allSnapshotsAndFutures: TelemetrySnapshot[];
  currentSnapshotIndex: number;
  isFuture: boolean;
  setCurrentSnapshot: (snap: TelemetrySnapshot) => void;
  addFutureSnapshots: (snaps: TelemetrySnapshot[]) => void;
  addSnapshot: (snap: TelemetrySnapshot) => void;
  selectSnapshot: (index: number) => void;
};

export const SnapshotContext = createContext<SnapshotContextType>({
  allSnapshots: [],
  currentSnapshot: null,
  futureSnapshots: [],
  isFuture: false,
  allSnapshotsAndFutures: [],
  currentSnapshotIndex: 0,
  setCurrentSnapshot: () => {},
  addFutureSnapshots: () => {},
  addSnapshot: () => {},
  selectSnapshot: () => {},
});

export default function SnapshotProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [allSnapshots, setAllSnapshots] = useState<TelemetrySnapshot[]>([
    {
        "Lap": "1",
        "Time": "0:03:31",
        "Lap Time": "03:31.0",
        "Sector 1 Time (s)": "74.23",
        "Sector 2 Time (s)": "74.22",
        "Sector 3 Time (s)": "63.47",
        "Top Speed (km/h)": "233.6",
        "Tire Pressure (PSI)": "29.9",
        "Fuel Level (%)": "97.5",
        "Tire Type": "Medium",
        "Driver": "E. GUERRIERI",
        "Pit Stop": "No",
        "Pit Time (sec)": "",
        "Tire Pressure FL": "30.29",
        "Tire Pressure FR": "29.09",
        "Tire Pressure RL": "28.96",
        "Tire Pressure RR": "29.29",
        "Tire Temp Inner FL": "87.3",
        "Tire Temp Mid FL": "82.9",
        "Tire Temp Outer FL": "87.0",
        "Tire Temp Inner FR": "93.8",
        "Tire Temp Mid FR": "100.6",
        "Tire Temp Outer FR": "80.7",
        "Tire Temp Inner RL": "95.4",
        "Tire Temp Mid RL": "93.3",
        "Tire Temp Outer RL": "87.6",
        "Tire Temp Inner RR": "104.3",
        "Tire Temp Mid RR": "97.8",
        "Tire Temp Outer RR": "104.7",
        "Tire Wear FL": "8.6",
        "Tire Wear FR": "5.9",
        "Tire Wear RL": "0.4",
        "Tire Wear RR": "1.7",
        "Brake Temp Front": "798.0",
        "Brake Temp Rear": "382.2",
        "Brake Pressure Front": "80.2",
        "Brake Pressure Rear": "89.5",
        "Brake Bias": "59.6",
        "Oil Temp": "100.1",
        "Water Temp": "98.1",
        "Fuel Burn per Lap": "2.07",
        "Throttle Map": "Aggressive",
        "Engine Map Mode": "Safe",
        "ERS State of Charge": "62.8",
        "ERS Battery Temp": "49.8",
        "ERS Deploy Mode": "Medium",
        "Throttle %": "84.4",
        "Brake %": "4.0",
        "Steering Angle": "-39.9",
        "Steering Correction": "0.42",
        "Lap Delta": "-0.72"
    },
    {
        "Lap": "2",
        "Time": "0:07:04",
        "Lap Time": "03:32.0",
        "Sector 1 Time (s)": "74.4",
        "Sector 2 Time (s)": "74.39",
        "Sector 3 Time (s)": "63.97",
        "Top Speed (km/h)": "233.0",
        "Tire Pressure (PSI)": "29.7",
        "Fuel Level (%)": "95.0",
        "Tire Type": "Medium",
        "Driver": "E. GUERRIERI",
        "Pit Stop": "No",
        "Pit Time (sec)": "",
        "Tire Pressure FL": "30.03",
        "Tire Pressure FR": "29.86",
        "Tire Pressure RL": "28.6",
        "Tire Pressure RR": "29.54",
        "Tire Temp Inner FL": "105.9",
        "Tire Temp Mid FL": "101.3",
        "Tire Temp Outer FL": "93.6",
        "Tire Temp Inner FR": "88.2",
        "Tire Temp Mid FR": "95.8",
        "Tire Temp Outer FR": "90.8",
        "Tire Temp Inner RL": "91.5",
        "Tire Temp Mid RL": "94.4",
        "Tire Temp Outer RL": "81.5",
        "Tire Temp Inner RR": "85.6",
        "Tire Temp Mid RR": "84.3",
        "Tire Temp Outer RR": "107.5",
        "Tire Wear FL": "8.0",
        "Tire Wear FR": "6.9",
        "Tire Wear RL": "9.7",
        "Tire Wear RR": "3.2",
        "Brake Temp Front": "785.2",
        "Brake Temp Rear": "437.3",
        "Brake Pressure Front": "102.3",
        "Brake Pressure Rear": "66.5",
        "Brake Bias": "57.6",
        "Oil Temp": "95.3",
        "Water Temp": "86.7",
        "Fuel Burn per Lap": "1.84",
        "Throttle Map": "Economy",
        "Engine Map Mode": "Safe",
        "ERS State of Charge": "51.2",
        "ERS Battery Temp": "40.0",
        "ERS Deploy Mode": "High",
        "Throttle %": "21.2",
        "Brake %": "53.7",
        "Steering Angle": "-140.5",
        "Steering Correction": "0.55",
        "Lap Delta": "-1.08"
    },
    {
        "Lap": "3",
        "Time": "0:10:38",
        "Lap Time": "03:33.0",
        "Sector 1 Time (s)": "74.8",
        "Sector 2 Time (s)": "74.63",
        "Sector 3 Time (s)": "63.9",
        "Top Speed (km/h)": "233.8",
        "Tire Pressure (PSI)": "29.6",
        "Fuel Level (%)": "92.5",
        "Tire Type": "Medium",
        "Driver": "E. GUERRIERI",
        "Pit Stop": "No",
        "Pit Time (sec)": "",
        "Tire Pressure FL": "29.74",
        "Tire Pressure FR": "30.11",
        "Tire Pressure RL": "29.09",
        "Tire Pressure RR": "29.65",
        "Tire Temp Inner FL": "95.6",
        "Tire Temp Mid FL": "89.2",
        "Tire Temp Outer FL": "91.6",
        "Tire Temp Inner FR": "93.5",
        "Tire Temp Mid FR": "104.6",
        "Tire Temp Outer FR": "108.0",
        "Tire Temp Inner RL": "103.3",
        "Tire Temp Mid RL": "105.5",
        "Tire Temp Outer RL": "93.4",
        "Tire Temp Inner RR": "80.3",
        "Tire Temp Mid RR": "105.8",
        "Tire Temp Outer RR": "99.7",
        "Tire Wear FL": "0.4",
        "Tire Wear FR": "3.9",
        "Tire Wear RL": "5.0",
        "Tire Wear RR": "3.1",
        "Brake Temp Front": "680.8",
        "Brake Temp Rear": "334.4",
        "Brake Pressure Front": "85.8",
        "Brake Pressure Rear": "89.9",
        "Brake Bias": "61.1",
        "Oil Temp": "107.8",
        "Water Temp": "103.8",
        "Fuel Burn per Lap": "1.87",
        "Throttle Map": "Economy",
        "Engine Map Mode": "Quali",
        "ERS State of Charge": "36.4",
        "ERS Battery Temp": "38.7",
        "ERS Deploy Mode": "Medium",
        "Throttle %": "23.6",
        "Brake %": "87.0",
        "Steering Angle": "-162.1",
        "Steering Correction": "-3.32",
        "Lap Delta": "-1.31"
    },
    {
        "Lap": "4",
        "Time": "0:14:09",
        "Lap Time": "03:31.0",
        "Sector 1 Time (s)": "74.24",
        "Sector 2 Time (s)": "74.16",
        "Sector 3 Time (s)": "63.49",
        "Top Speed (km/h)": "230.2",
        "Tire Pressure (PSI)": "29.4",
        "Fuel Level (%)": "90.0",
        "Tire Type": "Medium",
        "Driver": "E. GUERRIERI",
        "Pit Stop": "No",
        "Pit Time (sec)": "",
        "Tire Pressure FL": "30.39",
        "Tire Pressure FR": "30.02",
        "Tire Pressure RL": "29.96",
        "Tire Pressure RR": "29.06",
        "Tire Temp Inner FL": "99.5",
        "Tire Temp Mid FL": "94.7",
        "Tire Temp Outer FL": "91.2",
        "Tire Temp Inner FR": "81.8",
        "Tire Temp Mid FR": "97.6",
        "Tire Temp Outer FR": "96.2",
        "Tire Temp Inner RL": "108.3",
        "Tire Temp Mid RL": "84.2",
        "Tire Temp Outer RL": "93.2",
        "Tire Temp Inner RR": "99.0",
        "Tire Temp Mid RR": "97.4",
        "Tire Temp Outer RR": "90.4",
        "Tire Wear FL": "8.3",
        "Tire Wear FR": "1.8",
        "Tire Wear RL": "5.7",
        "Tire Wear RR": "2.9",
        "Brake Temp Front": "570.4",
        "Brake Temp Rear": "553.8",
        "Brake Pressure Front": "89.0",
        "Brake Pressure Rear": "68.0",
        "Brake Bias": "60.9",
        "Oil Temp": "96.9",
        "Water Temp": "88.3",
        "Fuel Burn per Lap": "1.99",
        "Throttle Map": "Balanced",
        "Engine Map Mode": "Race",
        "ERS State of Charge": "32.8",
        "ERS Battery Temp": "45.3",
        "ERS Deploy Mode": "Medium",
        "Throttle %": "73.2",
        "Brake %": "8.1",
        "Steering Angle": "-178.2",
        "Steering Correction": "1.67",
        "Lap Delta": "-1.75"
    },
    {
        "Lap": "5",
        "Time": "0:17:42",
        "Lap Time": "03:32.0",
        "Sector 1 Time (s)": "74.16",
        "Sector 2 Time (s)": "74.55",
        "Sector 3 Time (s)": "63.79",
        "Top Speed (km/h)": "234.0",
        "Tire Pressure (PSI)": "29.3",
        "Fuel Level (%)": "87.5",
        "Tire Type": "Medium",
        "Driver": "E. GUERRIERI",
        "Pit Stop": "No",
        "Pit Time (sec)": "",
        "Tire Pressure FL": "30.33",
        "Tire Pressure FR": "30.49",
        "Tire Pressure RL": "28.67",
        "Tire Pressure RR": "29.22",
        "Tire Temp Inner FL": "91.0",
        "Tire Temp Mid FL": "88.8",
        "Tire Temp Outer FL": "104.3",
        "Tire Temp Inner FR": "94.4",
        "Tire Temp Mid FR": "107.3",
        "Tire Temp Outer FR": "105.4",
        "Tire Temp Inner RL": "100.2",
        "Tire Temp Mid RL": "99.2",
        "Tire Temp Outer RL": "101.1",
        "Tire Temp Inner RR": "90.8",
        "Tire Temp Mid RR": "83.4",
        "Tire Temp Outer RR": "108.4",
        "Tire Wear FL": "0.6",
        "Tire Wear FR": "1.6",
        "Tire Wear RL": "0.5",
        "Tire Wear RR": "2.7",
        "Brake Temp Front": "730.0",
        "Brake Temp Rear": "671.4",
        "Brake Pressure Front": "87.2",
        "Brake Pressure Rear": "79.1",
        "Brake Bias": "55.9",
        "Oil Temp": "99.2",
        "Water Temp": "91.9",
        "Fuel Burn per Lap": "2.0",
        "Throttle Map": "Economy",
        "Engine Map Mode": "Quali",
        "ERS State of Charge": "21.5",
        "ERS Battery Temp": "36.5",
        "ERS Deploy Mode": "High",
        "Throttle %": "51.2",
        "Brake %": "6.0",
        "Steering Angle": "74.4",
        "Steering Correction": "4.43",
        "Lap Delta": "1.18"
    },
    {
        "Lap": "6",
        "Time": "0:21:15",
        "Lap Time": "03:32.0",
        "Sector 1 Time (s)": "74.5",
        "Sector 2 Time (s)": "74.47",
        "Sector 3 Time (s)": "63.65",
        "Top Speed (km/h)": "232.6",
        "Tire Pressure (PSI)": "29.1",
        "Fuel Level (%)": "85.0",
        "Tire Type": "Medium",
        "Driver": "E. GUERRIERI",
        "Pit Stop": "No",
        "Pit Time (sec)": "",
        "Tire Pressure FL": "29.72",
        "Tire Pressure FR": "29.4",
        "Tire Pressure RL": "28.72",
        "Tire Pressure RR": "29.47",
        "Tire Temp Inner FL": "102.8",
        "Tire Temp Mid FL": "90.7",
        "Tire Temp Outer FL": "108.8",
        "Tire Temp Inner FR": "100.2",
        "Tire Temp Mid FR": "108.7",
        "Tire Temp Outer FR": "108.8",
        "Tire Temp Inner RL": "93.5",
        "Tire Temp Mid RL": "82.2",
        "Tire Temp Outer RL": "98.1",
        "Tire Temp Inner RR": "87.7",
        "Tire Temp Mid RR": "107.5",
        "Tire Temp Outer RR": "101.5",
        "Tire Wear FL": "0.8",
        "Tire Wear FR": "1.5",
        "Tire Wear RL": "2.6",
        "Tire Wear RR": "2.0",
        "Brake Temp Front": "476.7",
        "Brake Temp Rear": "410.1",
        "Brake Pressure Front": "93.4",
        "Brake Pressure Rear": "84.9",
        "Brake Bias": "55.3",
        "Oil Temp": "95.9",
        "Water Temp": "92.6",
        "Fuel Burn per Lap": "1.95",
        "Throttle Map": "Balanced",
        "Engine Map Mode": "Safe",
        "ERS State of Charge": "35.6",
        "ERS Battery Temp": "44.9",
        "ERS Deploy Mode": "High",
        "Throttle %": "13.9",
        "Brake %": "87.0",
        "Steering Angle": "-117.2",
        "Steering Correction": "-2.59",
        "Lap Delta": "-1.31"
    },
    {
        "Lap": "7",
        "Time": "0:24:47",
        "Lap Time": "03:32.0",
        "Sector 1 Time (s)": "74.36",
        "Sector 2 Time (s)": "74.67",
        "Sector 3 Time (s)": "63.63",
        "Top Speed (km/h)": "232.0",
        "Tire Pressure (PSI)": "29.0",
        "Fuel Level (%)": "82.5",
        "Tire Type": "Medium",
        "Driver": "E. GUERRIERI",
        "Pit Stop": "No",
        "Pit Time (sec)": "",
        "Tire Pressure FL": "30.08",
        "Tire Pressure FR": "29.65",
        "Tire Pressure RL": "29.66",
        "Tire Pressure RR": "29.27",
        "Tire Temp Inner FL": "91.1",
        "Tire Temp Mid FL": "104.7",
        "Tire Temp Outer FL": "104.9",
        "Tire Temp Inner FR": "91.8",
        "Tire Temp Mid FR": "107.8",
        "Tire Temp Outer FR": "107.9",
        "Tire Temp Inner RL": "90.2",
        "Tire Temp Mid RL": "81.6",
        "Tire Temp Outer RL": "95.6",
        "Tire Temp Inner RR": "98.6",
        "Tire Temp Mid RR": "108.9",
        "Tire Temp Outer RR": "90.7",
        "Tire Wear FL": "2.7",
        "Tire Wear FR": "5.8",
        "Tire Wear RL": "4.7",
        "Tire Wear RR": "3.2",
        "Brake Temp Front": "645.5",
        "Brake Temp Rear": "414.8",
        "Brake Pressure Front": "99.1",
        "Brake Pressure Rear": "65.3",
        "Brake Bias": "59.3",
        "Oil Temp": "97.9",
        "Water Temp": "89.5",
        "Fuel Burn per Lap": "2.16",
        "Throttle Map": "Economy",
        "Engine Map Mode": "Race",
        "ERS State of Charge": "58.8",
        "ERS Battery Temp": "30.5",
        "ERS Deploy Mode": "Low",
        "Throttle %": "69.5",
        "Brake %": "75.1",
        "Steering Angle": "-0.1",
        "Steering Correction": "2.48",
        "Lap Delta": "-1.72"
    },
    {
        "Lap": "8",
        "Time": "0:28:19",
        "Lap Time": "03:31.0",
        "Sector 1 Time (s)": "74.06",
        "Sector 2 Time (s)": "73.98",
        "Sector 3 Time (s)": "63.39",
        "Top Speed (km/h)": "233.3",
        "Tire Pressure (PSI)": "28.8",
        "Fuel Level (%)": "80.0",
        "Tire Type": "Medium",
        "Driver": "E. GUERRIERI",
        "Pit Stop": "No",
        "Pit Time (sec)": "",
        "Tire Pressure FL": "29.94",
        "Tire Pressure FR": "29.29",
        "Tire Pressure RL": "28.64",
        "Tire Pressure RR": "29.32",
        "Tire Temp Inner FL": "108.3",
        "Tire Temp Mid FL": "99.8",
        "Tire Temp Outer FL": "82.0",
        "Tire Temp Inner FR": "99.9",
        "Tire Temp Mid FR": "98.0",
        "Tire Temp Outer FR": "84.9",
        "Tire Temp Inner RL": "85.6",
        "Tire Temp Mid RL": "90.4",
        "Tire Temp Outer RL": "107.3",
        "Tire Temp Inner RR": "83.3",
        "Tire Temp Mid RR": "109.4",
        "Tire Temp Outer RR": "89.9",
        "Tire Wear FL": "9.7",
        "Tire Wear FR": "1.6",
        "Tire Wear RL": "7.8",
        "Tire Wear RR": "3.9",
        "Brake Temp Front": "609.3",
        "Brake Temp Rear": "682.7",
        "Brake Pressure Front": "91.6",
        "Brake Pressure Rear": "82.0",
        "Brake Bias": "56.0",
        "Oil Temp": "102.1",
        "Water Temp": "99.7",
        "Fuel Burn per Lap": "2.08",
        "Throttle Map": "Balanced",
        "Engine Map Mode": "Race",
        "ERS State of Charge": "63.9",
        "ERS Battery Temp": "43.6",
        "ERS Deploy Mode": "High",
        "Throttle %": "41.6",
        "Brake %": "76.1",
        "Steering Angle": "140.3",
        "Steering Correction": "-2.89",
        "Lap Delta": "1.74"
    },
    {
        "Lap": "9",
        "Time": "0:31:52",
        "Lap Time": "03:33.0",
        "Sector 1 Time (s)": "74.74",
        "Sector 2 Time (s)": "74.69",
        "Sector 3 Time (s)": "63.75",
        "Top Speed (km/h)": "233.8",
        "Tire Pressure (PSI)": "28.7",
        "Fuel Level (%)": "77.5",
        "Tire Type": "Medium",
        "Driver": "E. GUERRIERI",
        "Pit Stop": "No",
        "Pit Time (sec)": "",
        "Tire Pressure FL": "30.38",
        "Tire Pressure FR": "29.82",
        "Tire Pressure RL": "29.57",
        "Tire Pressure RR": "29.44",
        "Tire Temp Inner FL": "101.8",
        "Tire Temp Mid FL": "84.8",
        "Tire Temp Outer FL": "101.0",
        "Tire Temp Inner FR": "86.0",
        "Tire Temp Mid FR": "109.9",
        "Tire Temp Outer FR": "109.5",
        "Tire Temp Inner RL": "101.8",
        "Tire Temp Mid RL": "93.7",
        "Tire Temp Outer RL": "82.5",
        "Tire Temp Inner RR": "107.9",
        "Tire Temp Mid RR": "90.8",
        "Tire Temp Outer RR": "99.6",
        "Tire Wear FL": "5.7",
        "Tire Wear FR": "5.7",
        "Tire Wear RL": "2.4",
        "Tire Wear RR": "2.7",
        "Brake Temp Front": "743.1",
        "Brake Temp Rear": "530.8",
        "Brake Pressure Front": "97.5",
        "Brake Pressure Rear": "77.0",
        "Brake Bias": "56.2",
        "Oil Temp": "101.3",
        "Water Temp": "99.4",
        "Fuel Burn per Lap": "1.85",
        "Throttle Map": "Aggressive",
        "Engine Map Mode": "Quali",
        "ERS State of Charge": "85.8",
        "ERS Battery Temp": "44.7",
        "ERS Deploy Mode": "Medium",
        "Throttle %": "80.5",
        "Brake %": "2.8",
        "Steering Angle": "120.4",
        "Steering Correction": "-1.42",
        "Lap Delta": "-0.38"
    },
    {
        "Lap": "10",
        "Time": "0:35:25",
        "Lap Time": "03:32.0",
        "Sector 1 Time (s)": "74.67",
        "Sector 2 Time (s)": "74.45",
        "Sector 3 Time (s)": "63.79",
        "Top Speed (km/h)": "232.8",
        "Tire Pressure (PSI)": "28.5",
        "Fuel Level (%)": "75.0",
        "Tire Type": "Medium",
        "Driver": "E. GUERRIERI",
        "Pit Stop": "No",
        "Pit Time (sec)": "",
        "Tire Pressure FL": "29.04",
        "Tire Pressure FR": "29.75",
        "Tire Pressure RL": "28.72",
        "Tire Pressure RR": "28.98",
        "Tire Temp Inner FL": "101.9",
        "Tire Temp Mid FL": "91.2",
        "Tire Temp Outer FL": "95.1",
        "Tire Temp Inner FR": "86.0",
        "Tire Temp Mid FR": "108.1",
        "Tire Temp Outer FR": "101.5",
        "Tire Temp Inner RL": "81.7",
        "Tire Temp Mid RL": "109.2",
        "Tire Temp Outer RL": "104.1",
        "Tire Temp Inner RR": "107.2",
        "Tire Temp Mid RR": "81.5",
        "Tire Temp Outer RR": "90.2",
        "Tire Wear FL": "7.6",
        "Tire Wear FR": "6.5",
        "Tire Wear RL": "2.5",
        "Tire Wear RR": "5.2",
        "Brake Temp Front": "631.5",
        "Brake Temp Rear": "415.8",
        "Brake Pressure Front": "108.8",
        "Brake Pressure Rear": "90.0",
        "Brake Bias": "57.4",
        "Oil Temp": "94.2",
        "Water Temp": "96.5",
        "Fuel Burn per Lap": "2.04",
        "Throttle Map": "Economy",
        "Engine Map Mode": "Quali",
        "ERS State of Charge": "66.4",
        "ERS Battery Temp": "36.1",
        "ERS Deploy Mode": "High",
        "Throttle %": "27.1",
        "Brake %": "61.7",
        "Steering Angle": "29.5",
        "Steering Correction": "4.18",
        "Lap Delta": "-0.55"
    }
]);
  const [currentSnapshot, setCurrentSnapshot] = useState<TelemetrySnapshot | null>(null);
  const [currentSnapshotIndex, setCurrentSnapshotIndex] = useState<number>(0);
  const [futureSnapshots, setFutureSnapshots] = useState<TelemetrySnapshot[]>([]);

  useEffect(() => {
    console.log(allSnapshots)
  }, [allSnapshots])

  const allSnapshotsAndFutures = [ ...allSnapshots, ...futureSnapshots ];

  const isFuture = currentSnapshotIndex > allSnapshots.length - 1;

  const addSnapshot = (snap: TelemetrySnapshot) => {
    setAllSnapshots((val) => [...val, snap]);
  };

  const selectSnapshot = (index: number) => {
    setCurrentSnapshotIndex(index);
    setCurrentSnapshot(allSnapshotsAndFutures[index]);
  }

  const addFutureSnapshots = (snaps: TelemetrySnapshot[]) => {
    setFutureSnapshots((val) => [...val, ...snaps]);
  }

  return (
    <SnapshotContext.Provider
      value={{
        addSnapshot,
        allSnapshots,
        currentSnapshot,
        setCurrentSnapshot,
        futureSnapshots,
        addFutureSnapshots,
        selectSnapshot,
        currentSnapshotIndex,
        allSnapshotsAndFutures,
        isFuture,
      }}
    >
      {children}
    </SnapshotContext.Provider>
  );
}
