export const API_ROUTES = {
  TELEMETRY: 'api/telemetry'
}

export enum TelemetryKeys {
  LAP = "Lap",
  TIME = "Time",
  LAP_TIME = "Lap Time",
  SECTOR_1_TIME_S = "Sector 1 Time (s)",
  SECTOR_2_TIME_S = "Sector 2 Time (s)",
  SECTOR_3_TIME_S = "Sector 3 Time (s)",
  TOP_SPEED_KMH = "Top Speed (km/h)",
  TIRE_PRESSURE_PSI = "Tire Pressure (PSI)",
  FUEL_LEVEL_PERCENT = "Fuel Level (%)",
  TIRE_TYPE = "Tire Type",
  DRIVER = "Driver",
  PIT_STOP = "Pit Stop",
  PIT_TIME_SEC = "Pit Time (sec)",
  TIRE_PRESSURE_FL = "Tire Pressure FL",
  TIRE_PRESSURE_FR = "Tire Pressure FR",
  TIRE_PRESSURE_RL = "Tire Pressure RL",
  TIRE_PRESSURE_RR = "Tire Pressure RR",
  TIRE_TEMP_INNER_FL = "Tire Temp Inner FL",
  TIRE_TEMP_MID_FL = "Tire Temp Mid FL",
  TIRE_TEMP_OUTER_FL = "Tire Temp Outer FL",
  TIRE_TEMP_INNER_FR = "Tire Temp Inner FR",
  TIRE_TEMP_MID_FR = "Tire Temp Mid FR",
  TIRE_TEMP_OUTER_FR = "Tire Temp Outer FR",
  TIRE_TEMP_INNER_RL = "Tire Temp Inner RL",
  TIRE_TEMP_MID_RL = "Tire Temp Mid RL",
  TIRE_TEMP_OUTER_RL = "Tire Temp Outer RL",
  TIRE_TEMP_INNER_RR = "Tire Temp Inner RR",
  TIRE_TEMP_MID_RR = "Tire Temp Mid RR",
  TIRE_TEMP_OUTER_RR = "Tire Temp Outer RR",
  TIRE_WEAR_FL = "Tire Wear FL",
  TIRE_WEAR_FR = "Tire Wear FR",
  TIRE_WEAR_RL = "Tire Wear RL",
  TIRE_WEAR_RR = "Tire Wear RR",
  BRAKE_TEMP_FRONT = "Brake Temp Front",
  BRAKE_TEMP_REAR = "Brake Temp Rear",
  BRAKE_PRESSURE_FRONT = "Brake Pressure Front",
  BRAKE_PRESSURE_REAR = "Brake Pressure Rear",
  BRAKE_BIAS = "Brake Bias",
  OIL_TEMP = "Oil Temp",
  WATER_TEMP = "Water Temp",
  FUEL_BURN_PER_LAP = "Fuel Burn per Lap",
  THROTTLE_MAP = "Throttle Map",
  ENGINE_MAP_MODE = "Engine Map Mode",
  ERS_STATE_OF_CHARGE = "ERS State of Charge",
  ERS_BATTERY_TEMP = "ERS Battery Temp",
  ERS_DEPLOY_MODE = "ERS Deploy Mode",
  THROTTLE_PERCENT = "Throttle %",
  BRAKE_PERCENT = "Brake %",
  STEERING_ANGLE = "Steering Angle",
  STEERING_CORRECTION = "Steering Correction",
  LAP_DELTA = "Lap Delta"
}